name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: self-hosted

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4


      # 2. Check environment
      - name: Check Environment
        shell: powershell
        run: |
          node -v
          npm -v
          docker --version
          dir


      # 3. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24


      # 4. Install dependencies
      - name: Install Dependencies
        shell: powershell
        run: |
          npm install


      # 5. Build React application
      - name: Build React App
        shell: powershell
        run: |
          npm run build


      # 6. Build Docker image
      - name: Build Docker Image
        shell: powershell
        run: |
          docker build -t weather-app:latest .


      # 7. Stop existing container
      - name: Stop Old Container
        shell: powershell
        run: |
          docker stop weather-container
          if ($LASTEXITCODE -ne 0) {
            Write-Host "No running container found"
          }


      # 8. Remove existing container
      - name: Remove Old Container
        shell: powershell
        run: |
          docker rm weather-container
          if ($LASTEXITCODE -ne 0) {
            Write-Host "No old container found"
          }


      # 9. Run new container
      - name: Run New Container
        shell: powershell
        run: |
          docker run -d `
          -p 8080:80 `
          --name weather-container `
          weather-app:latest


      # 10. Verify deployment
      - name: Check Running Container
        shell: powershell
        run: |
          docker ps