name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # 3. Check Environment
      - name: Check Environment
        shell: powershell
        run: |
          Write-Host "===== Environment ====="
          node -v
          npm -v
          docker --version
          docker ps -a
          Get-Date

      # 4. Install Dependencies
      - name: Install Dependencies
        shell: powershell
        run: |
          npm install

      # 5. Build React Application
      - name: Build React App
        shell: powershell
        run: |
          npm run build

      # 6. Build Docker Image
      - name: Build Docker Image
        shell: powershell
        run: |
          docker build `
            --build-arg VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }} `
            -t weather-app:latest .

      # 7. Stop Existing Container
      - name: Stop Old Container
        shell: powershell
        run: |
          docker stop weather-container 2>$null

      # 8. Remove Existing Container
      - name: Remove Old Container
        shell: powershell
        run: |
          docker rm weather-container 2>$null

      # 9. Run New Container
      - name: Run New Container
        shell: powershell
        run: |
          docker run -d `
            -p 8080:80 `
            --name weather-container `
            weather-app:latest

      # 10. Wait for Container
      - name: Wait for Application
        shell: powershell
        run: |
          Start-Sleep -Seconds 5

      # 11. Verify Deployment
      - name: Verify Deployment
        shell: powershell
        run: |
          docker ps

          $running = docker inspect -f "{{.State.Running}}" weather-container

          if ($running -ne "true") {
            throw "Container is not running!"
          }

          Write-Host ""
          Write-Host "===================================="
          Write-Host "Container is running successfully."
          Write-Host "===================================="

          docker logs weather-container --tail 10

      # 12. Cleanup Docker Images
      - name: Cleanup Docker Images
        shell: powershell
        run: |
          docker image prune -f

      # 13. Deployment Completed
      - name: Deployment Completed
        shell: powershell
        run: |
          Write-Host ""
          Write-Host "========================================="
          Write-Host "React Weather App Deployed Successfully"
          Write-Host "URL : http://localhost:8080"
          Write-Host "========================================="